package mocks

import (
	"github.com/esmaeel67/golang-tdd.git/calculator"
	"github.com/stretchr/testify/mock"
)

// OperationProcessor is an autogenerated mock type for the OperationProcessor type
type OperationProcessor struct {
	mock.Mock
}

func (_m *OperationProcessor) ProcessOperation(operation calculator.Operation) (*string, error) {
	ret := _m.Called(operation)

	var r0 *string
	if rf, ok := ret.Get(0).(func(calculator.Operation) *string); ok {
		r0 = rf(operation)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(calculator.Operation) error); ok {
		r1 = rf(operation)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type mockConstructorTestingTNewOperationProcessor interface {
	mock.TestingT
	Cleanup(func())
}

func NewOperationProcessor(t mockConstructorTestingTNewOperationProcessor) *OperationProcessor {
	mock := &OperationProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		mock.AssertExpectations(t)
	})

	return mock
}
